---

dist: xenial # we need xenial to have mysql 5.7

language: java
jdk: openjdk8 # oraclejdk8 is no longer supported by travis-ci

env:
  global:
  - JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
  - PATH=$(echo "$PATH" | sed -e 's/:\/usr\/local\/lib\/jvm\/openjdk11\/bin//')


before_install:
  # Debian has since stretch an OCR-B font and a fonts-ocr-a
  # Xenial only has fonts-ocr-a
  - sudo apt-get install -y librxtx-java fonts-ocr-a libreoffice

install: mvn -V --quiet clean

script: xvfb-run --server-args="-screen 4 1280x1024x24" mvn -V clean install -f h2/pom.xml

notifications:
  email:
  - niklaus.giger@member.fsf.org

cache:
  directories:
  - $HOME/.m2
